version: '3.8'

services:

  skywardlease.database:
    expose:
      - 5432  
    environment:         
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}




