version: '3.8'

services:

  skywardlease.database:
    ports:
      - 5431:5432
    expose:
      - 5432  
    environment:  
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}




