# Generated by Django 4.2.10 on 2024-02-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_role_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('aircraft_name', models.CharField(max_length=254)),
                ('aircraft_description', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertiesRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_rule', to='aircraft.propertiesrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeasedAircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lease_start', models.DateTimeField()),
                ('lease_end', models.DateTimeField()),
                ('lease_price', models.FloatField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leased_aircraft', to='aircraft.aircraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaser_user', to='identity.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='aircraft_properties', to='aircraft.properties'),
        ),
    ]
