# Generated by Django 4.2.10 on 2024-02-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_user_role_alter_role_table_alter_user_table'),
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='aircrafts', to='aircraft.properties'),
        ),
        migrations.AlterField(
            model_name='leasedaircraft',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='aircraft.aircraft'),
        ),
        migrations.AlterField(
            model_name='leasedaircraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leased', to='identity.user'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='aircraft.propertiesrule'),
        ),
        migrations.AlterModelTable(
            name='aircraft',
            table='aircrafts',
        ),
        migrations.AlterModelTable(
            name='leasedaircraft',
            table='leased_aircrafts',
        ),
        migrations.AlterModelTable(
            name='properties',
            table='properties',
        ),
        migrations.AlterModelTable(
            name='propertiesrule',
            table='properties_rules',
        ),
    ]
