# Generated by Django 4.2.10 on 2024-02-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_rename_rule_properties_property_rule_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='PropertiesRule',
            new_name='PropertyRule',
        ),
    ]
