# Generated by Django 4.2.10 on 2024-02-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_rename_properties_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
    ]
